const status = {
  pending: {
    ar: "معلقة",
    en: "Pending",
    fr: "En attente",
    de: "Ausstehend",
    es: "Pendiente",
    tr: "Beklemede",
    ru: "В ожидании",
    zh: "待处理",
    ko: "보류 중",
    pt: "Pendente",
    ur: "زیر التواء",
    ja: "保留中",
  },
  pendding: {
    ar: "معلقة",
    en: "Pending",
    fr: "En attente",
    de: "Ausstehend",
    es: "Pendiente",
    tr: "Beklemede",
    ru: "В ожидании",
    zh: "待处理",
    ko: "보류 중",
    pt: "Pendente",
    ur: "زیر التواء",
    ja: "保留中",
  },
  canceled: {
    ar: "ملغية",
    en: "Canceled",
    fr: "Annulée",
    de: "Storniert",
    es: "Cancelada",
    tr: "İptal edildi",
    ru: "Отменено",
    zh: "已取消",
    ko: "취소됨",
    pt: "Cancelada",
    ur: "منسوخ",
    ja: "キャンセル済み",
  },
  rejected: {
    ar: "مرفوضة",
    en: "Rejected",
    fr: "Rejetée",
    de: "Abgelehnt",
    es: "Rechazada",
    tr: "Reddedildi",
    ru: "Отклонено",
    zh: "已拒绝",
    ko: "거절됨",
    pt: "Rejeitada",
    ur: "مسترد",
    ja: "拒否されました",
  },
  CAPTURED: {
    ar: "مدفوعة",
    en: "Paid",
    fr: "Payée",
    de: "Bezahlt",
    es: "Pagada",
    tr: "Ödendi",
    ru: "Оплачено",
    zh: "已支付",
    ko: "결제 완료",
    pt: "Paga",
    ur: "ادا شدہ",
    ja: "支払い済み",
  },
};
export default status;
