const detailsCardPageText = {
  ar: {
    numberOfPeople: "عدد الأفراد",
    people: "أفراد",
    group: "للمجموعة",
    individual: "للفرد",
    bookingsCount: "عدد الحجوزات حتى الآن",
    freeCancelation: "متاح إلغاء الحجز مجانا",
    bookNowPayLater: "إحجز الآن إدفع لاحقا",
  },
  en: {
    numberOfPeople: "Number of people",
    people: "people",
    group: "Per group",
    individual: "Per person",
    bookingsCount: "Number of bookings so far",
    freeCancelation: "Free cancellation is available",
    bookNowPayLater: "Book now, pay later",
  },
  fr: {
    numberOfPeople: "Nombre de personnes",
    people: "personnes",
    group: "Par groupe",
    individual: "Par personne",
    bookingsCount: "Nombre de réservations jusqu'à présent",
    freeCancelation: "Annulation gratuite disponible",
    bookNowPayLater: "Réservez maintenant, payez plus tard",
  },
  de: {
    numberOfPeople: "Anzahl der Personen",
    people: "Personen",
    group: "Pro Gruppe",
    individual: "Pro Person",
    bookingsCount: "Anzahl der bisherigen Buchungen",
    freeCancelation: "Kostenlose Stornierung möglich",
    bookNowPayLater: "Jetzt buchen, später bezahlen",
  },
  es: {
    numberOfPeople: "Número de personas",
    people: "personas",
    group: "Por grupo",
    individual: "Por persona",
    bookingsCount: "Número de reservas hasta ahora",
    freeCancelation: "Cancelación gratuita disponible",
    bookNowPayLater: "Reserva ahora, paga después",
  },
  tr: {
    numberOfPeople: "Kişi sayısı",
    people: "kişi",
    group: "Grup için",
    individual: "Kişi başı",
    bookingsCount: "Şu ana kadar rezervasyon sayısı",
    freeCancelation: "Ücretsiz iptal mevcut",
    bookNowPayLater: "Şimdi rezervasyon yap, sonra öde",
  },
  ru: {
    numberOfPeople: "Количество человек",
    people: "человек",
    group: "За группу",
    individual: "За человека",
    bookingsCount: "Количество бронирований на данный момент",
    freeCancelation: "Доступна бесплатная отмена",
    bookNowPayLater: "Забронируй сейчас, плати позже",
  },
  zh: {
    numberOfPeople: "人数",
    people: "人",
    group: "每组",
    individual: "每人",
    bookingsCount: "到目前为止的预订数量",
    freeCancelation: "可免费取消",
    bookNowPayLater: "现在预订，稍后付款",
  },
  ko: {
    numberOfPeople: "인원 수",
    people: "명",
    group: "그룹당",
    individual: "1인당",
    bookingsCount: "현재까지 예약 수",
    freeCancelation: "무료 취소 가능",
    bookNowPayLater: "지금 예약하고 나중에 결제",
  },
  pt: {
    numberOfPeople: "Número de pessoas",
    people: "pessoas",
    group: "Por grupo",
    individual: "Por pessoa",
    bookingsCount: "Número de reservas até agora",
    freeCancelation: "Cancelamento gratuito disponível",
    bookNowPayLater: "Reserve agora, pague depois",
  },
  ur: {
    numberOfPeople: "افراد کی تعداد",
    people: "افراد",
    group: "گروپ کے لئے",
    individual: "فی فرد",
    bookingsCount: "اب تک کی بکنگز کی تعداد",
    freeCancelation: "مفت منسوخی دستیاب ہے",
    bookNowPayLater: "ابھی بک کریں، بعد میں ادا کریں",
  },
  ja: {
    numberOfPeople: "人数",
    people: "人",
    group: "グループごと",
    individual: "1人あたり",
    bookingsCount: "これまでの予約数",
    freeCancelation: "無料キャンセル可能",
    bookNowPayLater: "今すぐ予約、後で支払い",
  },
};
export default detailsCardPageText;
