import {
  faGlobe,
  faHandshake,
  faHeadphones,
  faMoneyBillWave,
  faSackDollar,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import CheckIcon from "assets/Icons/CheckIcon";
import PayIcon from "assets/images/IconsBooks/PayIcon";
import Star from "assets/images/IconsBooks/Star";

export const cardsBooks = [
  {
    id: 0,
    icon: <FontAwesomeIcon icon={faHeadphones} className="font-awesome" />,
    title: {
      ar: "خدمة عملاء متميزة",
      en: "Excellent Customer Service",
      fr: "Service client exceptionnel",
      de: "Hervorragender Kundenservice",
      es: "Atención al cliente excepcional",
      tr: "Mükemmel Müşteri Hizmeti",
      ru: "Отличное обслуживание клиентов",
      zh: "卓越的客户服务",
      ko: "우수한 고객 서비스",
      pt: "Atendimento ao Cliente Excelente",
      ur: "شاندار کسٹمر سروس",
      ja: "優れたカスタマーサービス",
    },
    text: {
      ar: "فريق دعم متواجد دائمًا للرد على استفساراتك ومساعدتك في كل خطوة من رحلتك، لضمان تجربة سلسة ومريحة.",
      en: "A dedicated support team always available to answer your questions and assist you every step of the way, ensuring a smooth and comfortable experience.",
      fr: "Une équipe de support toujours disponible pour répondre à vos questions et vous accompagner à chaque étape, garantissant une expérience fluide et agréable.",
      de: "Ein Support-Team steht Ihnen jederzeit zur Verfügung, um Ihre Fragen zu beantworten und Sie bei jedem Schritt zu unterstützen – für ein reibungsloses Erlebnis.",
      es: "Un equipo de soporte siempre disponible para responder tus preguntas y ayudarte en cada paso, asegurando una experiencia fluida y cómoda.",
      tr: "Sorularınızı yanıtlamak ve yolculuğunuzun her adımında size yardımcı olmak için her zaman hazır bir destek ekibiyle, sorunsuz ve konforlu bir deneyim yaşayın.",
      ru: "Команда поддержки всегда готова помочь вам на каждом этапе, обеспечивая комфортный и плавный опыт.",
      zh: "专属支持团队随时为您解答疑问并在每一步提供帮助，确保流畅舒适的体验。",
      ko: "언제나 질문에 답변하고 여정을 돕는 지원팀이 있어 원활하고 편안한 경험을 보장합니다.",
      pt: "Uma equipe de suporte dedicada sempre disponível para responder às suas dúvidas e ajudá-lo em cada etapa, garantindo uma experiência tranquila.",
      ur: "ہمیشہ دستیاب سپورٹ ٹیم جو آپ کی ہر ضرورت میں مدد کرے تاکہ تجربہ آرام دہ اور آسان ہو۔",
      ja: "専任のサポートチームが常に質問に答え、旅のあらゆる段階をサポートします。",
    },
  },
  {
    id: 1,
    icon: <PayIcon />,
    title: {
      ar: "بوابة دفع آمنة",
      en: "Secure Payment Gateway",
      fr: "Passerelle de paiement sécurisée",
      de: "Sicheres Zahlungsportal",
      es: "Pasarela de pago segura",
      tr: "Güvenli Ödeme Sistemi",
      ru: "Безопасный платежный шлюз",
      zh: "安全支付网关",
      ko: "안전한 결제 게이트웨이",
      pt: "Portal de Pagamento Seguro",
      ur: "محفوظ ادائیگی کا نظام",
      ja: "安全な決済ゲートウェイ",
    },
    text: {
      ar: "احجز وادفع بثقة من خلال نظام دفع محمي ومتوافق مع أعلى معايير الأمان الإلكتروني.",
      en: "Book and pay with confidence through a secure system that complies with the highest cybersecurity standards.",
      fr: "Réservez et payez en toute confiance grâce à un système sécurisé conforme aux normes de cybersécurité les plus élevées.",
      de: "Buchen und bezahlen Sie mit Vertrauen über ein sicheres System, das den höchsten Sicherheitsstandards entspricht.",
      es: "Reserva y paga con confianza a través de un sistema seguro que cumple con los más altos estándares de seguridad.",
      tr: "En yüksek güvenlik standartlarına uygun güvenli bir sistem üzerinden güvenle ödeme yapın.",
      ru: "Бронируйте и оплачивайте через безопасную систему, соответствующую самым высоким стандартам.",
      zh: "通过符合最高安全标准的安全系统放心预订和支付。",
      ko: "최고 수준의 보안 기준을 준수하는 안전한 시스템으로 예약하고 결제하세요.",
      pt: "Reserve e pague com confiança através de um sistema seguro em conformidade com os mais altos padrões.",
      ur: "محفوظ نظام کے ذریعے اعتماد سے بکنگ اور ادائیگی کریں۔",
      ja: "最高水準のセキュリティ基準に準拠した安全なシステムで安心して予約・支払いができます。",
    },
  },
  {
    id: 2,
    icon: <FontAwesomeIcon icon={faGlobe} className="font-awesome" />,
    title: {
      ar: "متعدد اللغات",
      en: "Multilingual",
      fr: "Multilingue",
      de: "Mehrsprachig",
      es: "Multilingüe",
      tr: "Çok Dilli",
      ru: "Многоязычный",
      zh: "多语言",
      ko: "다국어 지원",
      pt: "Multilíngue",
      ur: "کثیر اللسانی",
      ja: "多言語対応",
    },
    text: {
      ar: "منصة متاحة بـ12 لغة لتسهيل تجربة الحجز لجميع المستخدمين حول العالم، بلغتك المفضلة.",
      en: "A platform available in 12 languages to make booking easier for all users worldwide, in your preferred language.",
      fr: "Une plateforme disponible en 12 langues pour faciliter la réservation pour tous les utilisateurs dans le monde, dans votre langue préférée.",
      de: "Eine Plattform in 12 Sprachen verfügbar, um allen Nutzern weltweit das Buchen in ihrer bevorzugten Sprache zu erleichtern.",
      es: "Una plataforma disponible en 12 idiomas para facilitar las reservas a todos los usuarios en todo el mundo, en su idioma preferido.",
      tr: "Dünya genelindeki tüm kullanıcılar için rezervasyonu kolaylaştırmak amacıyla 12 dilde hizmet veren platform.",
      ru: "Платформа доступна на 12 языках, чтобы упростить бронирование для пользователей по всему миру на их любимом языке.",
      zh: "平台支持12种语言，方便全球用户以偏好的语言预订。",
      ko: "전 세계 사용자가 선호하는 언어로 예약할 수 있도록 12개 언어로 제공되는 플랫폼.",
      pt: "Uma plataforma disponível em 12 idiomas para facilitar as reservas em todo o mundo, no seu idioma preferido.",
      ur: "ایک پلیٹ فارم جو 12 زبانوں میں دستیاب ہے تاکہ دنیا بھر کے صارفین اپنی پسند کی زبان میں بکنگ کر سکیں۔",
      ja: "世界中のすべてのユーザーが好みの言語で予約できるように12言語で利用可能なプラットフォームです。",
    },
  },
  {
    id: 3,
    icon: <CheckIcon />,
    title: {
      ar: "موثق ومرخص",
      en: "Certified & Licensed",
      fr: "Certifié et agréé",
      de: "Zertifiziert & lizenziert",
      es: "Certificado y autorizado",
      tr: "Onaylı ve Lisanslı",
      ru: "Сертифицировано и лицензировано",
      zh: "认证和许可",
      ko: "인증 및 허가",
      pt: "Certificado e Licenciado",
      ur: "تصدیق شدہ اور لائسنس یافتہ",
      ja: "認定およびライセンス取得済み",
    },
    text: {
      ar: "جميع الخدمات والمرشدين المرخصين لضمان تجربة قانونية وآمنة مع التزام تام بالمعايير المحلية والدولية.",
      en: "All services and guides are licensed to ensure a legal and safe experience, fully compliant with local and international standards.",
      fr: "Tous les services et guides sont agréés pour garantir une expérience légale et sûre, conforme aux normes locales et internationales.",
      de: "Alle Dienstleistungen und Reiseführer sind lizenziert, um ein legales und sicheres Erlebnis gemäß den lokalen und internationalen Standards zu gewährleisten.",
      es: "Todos los servicios y guías están autorizados para garantizar una experiencia legal y segura conforme a los estándares locales e internacionales.",
      tr: "Tüm hizmetler ve rehberler, yasal ve güvenli bir deneyim için lisanslıdır ve yerel ile uluslararası standartlara uygundur.",
      ru: "Все услуги и гиды лицензированы для обеспечения законного и безопасного опыта в соответствии с местными и международными стандартами.",
      zh: "所有服务和导游均持有执照，确保合法、安全，并完全符合本地和国际标准。",
      ko: "모든 서비스와 가이드는 합법적이고 안전한 경험을 보장하기 위해 라이선스를 보유하고 있으며 현지 및 국제 표준을 준수합니다.",
      pt: "Todos os serviços e guias são licenciados para garantir uma experiência legal e segura, em conformidade com os padrões locais e internacionais.",
      ur: "تمام خدمات اور گائیڈز لائسنس یافتہ ہیں تاکہ ایک محفوظ اور قانونی تجربہ یقینی بنایا جا سکے۔",
      ja: "すべてのサービスとガイドは認定を受けており、国内外の基準に完全準拠した安全で合法的な体験を保証します。",
    },
  },
  {
    id: 4,
    icon: <FontAwesomeIcon icon={faHandshake} className="font-awesome" />,
    title: {
      ar: "شركاء موثوقون",
      en: "Trusted Partners",
      fr: "Partenaires de confiance",
      de: "Vertrauenswürdige Partner",
      es: "Socios de confianza",
      tr: "Güvenilir Ortaklar",
      ru: "Надежные партнёры",
      zh: "值得信赖的合作伙伴",
      ko: "신뢰할 수 있는 파트너",
      pt: "Parceiros de Confiança",
      ur: "قابل اعتماد شراکت دار",
      ja: "信頼できるパートナー",
    },
    text: {
      ar: "نتعاون فقط مع المرشدين، منظمي الجولات، والمتاجر الموثوق بها لتقديم تجربة عالية الجودة ومضمونة.",
      en: "We collaborate only with trusted guides, tour operators, and vendors to deliver a high-quality and guaranteed experience.",
      fr: "Nous collaborons uniquement avec des guides, des organisateurs de voyages et des commerçants de confiance pour offrir une expérience de qualité garantie.",
      de: "Wir arbeiten nur mit vertrauenswürdigen Reiseführern, Reiseveranstaltern und Anbietern zusammen, um ein hochwertiges und sicheres Erlebnis zu gewährleisten.",
      es: "Colaboramos solo con guías, operadores turísticos y comercios de confianza para garantizar una experiencia de alta calidad.",
      tr: "Yalnızca güvenilir rehberler, tur operatörleri ve satıcılarla işbirliği yaparak kaliteli ve güvenli bir deneyim sunuyoruz.",
      ru: "Мы сотрудничаем только с надежными гидами, туроператорами и поставщиками для обеспечения качественного и гарантированного опыта.",
      zh: "我们仅与值得信赖的导游、旅行社和商家合作，以确保高质量和可靠的体验。",
      ko: "신뢰할 수 있는 가이드, 투어 운영자, 판매자와만 협력하여 고품질의 보장된 경험을 제공합니다.",
      pt: "Colaboramos apenas com guias, operadores turísticos e fornecedores de confiança para garantir uma experiência de alta qualidade.",
      ur: "ہم صرف قابل اعتماد گائیڈز، ٹور آپریٹرز اور دکانداروں کے ساتھ تعاون کرتے ہیں تاکہ بہترین تجربہ فراہم کیا جا سکے۔",
      ja: "私たちは信頼できるガイド、ツアー運営者、販売者としか提携せず、高品質で保証された体験を提供します。",
    },
  },
  {
    id: 5,
    icon: <FontAwesomeIcon icon={faSackDollar} className="font-awesome" />,
    title: {
      ar: "عروض ومكافآت",
      en: "Offers & Rewards",
      fr: "Offres et récompenses",
      de: "Angebote & Belohnungen",
      es: "Ofertas y recompensas",
      tr: "Kampanyalar ve Ödüller",
      ru: "Предложения и награды",
      zh: "优惠和奖励",
      ko: "혜택 및 보상",
      pt: "Ofertas e Recompensas",
      ur: "آفرز اور انعامات",
      ja: "特典とリワード",
    },
    text: {
      ar: "استمتع بخصومات حصرية، عروض موسمية، وبرامج مكافآت تكافئ حجزك وتجعل كل تجربة أكثر قيمة.",
      en: "Enjoy exclusive discounts, seasonal offers, and reward programs that make each booking more valuable.",
      fr: "Profitez de réductions exclusives, d'offres saisonnières et de programmes de récompenses qui valorisent chaque réservation.",
      de: "Genießen Sie exklusive Rabatte, saisonale Angebote und Treueprogramme, die jede Buchung noch wertvoller machen.",
      es: "Disfruta de descuentos exclusivos, ofertas de temporada y programas de recompensas que hacen cada reserva más valiosa.",
      tr: "Her rezervasyonu daha değerli kılan özel indirimlerden, sezonluk kampanyalardan ve ödül programlarından yararlanın.",
      ru: "Наслаждайтесь эксклюзивными скидками, сезонными предложениями и программами вознаграждений, делающими каждое бронирование ещё ценнее.",
      zh: "享受独家折扣、季节性优惠和奖励计划，让每次预订更有价值。",
      ko: "독점 할인, 시즌별 혜택, 리워드 프로그램으로 예약 가치를 높이세요.",
      pt: "Aproveite descontos exclusivos, ofertas sazonais e programas de recompensas que valorizam cada reserva.",
      ur: "خصوصی رعایتیں، موسمی آفرز اور ریوارڈ پروگرامز سے لطف اندوز ہوں جو ہر بکنگ کو مزید قیمتی بناتے ہیں۔",
      ja: "限定割引、季節限定オファー、リワードプログラムで、予約ごとにより価値ある体験を楽しめます。",
    },
  },
  {
    id: 6,
    icon: <Star />,
    title: {
      ar: "مراجعات دقيقة",
      en: "Accurate Reviews",
      fr: "Avis précis",
      de: "Zuverlässige Bewertungen",
      es: "Reseñas confiables",
      tr: "Doğru İncelemeler",
      ru: "Точные отзывы",
      zh: "可靠的评价",
      ko: "정확한 리뷰",
      pt: "Avaliações Precisas",
      ur: "درست ریویوز",
      ja: "正確なレビュー",
    },
    text: {
      ar: "تقييمات ومراجعات موثوقة من المستخدمين تساعدك في اختيار أفضل الجولات والخدمات بثقة.",
      en: "Reliable user reviews and ratings help you confidently choose the best tours and services.",
      fr: "Des avis et évaluations fiables d'utilisateurs vous aident à choisir en toute confiance les meilleures visites et services.",
      de: "Zuverlässige Bewertungen von Nutzern helfen Ihnen, die besten Touren und Dienstleistungen sicher auszuwählen.",
      es: "Reseñas y valoraciones confiables de usuarios que te ayudan a elegir con confianza los mejores tours y servicios.",
      tr: "Güvenilir kullanıcı yorumları ve değerlendirmeleri, en iyi tur ve hizmetleri güvenle seçmenize yardımcı olur.",
      ru: "Надёжные отзывы пользователей помогают вам уверенно выбирать лучшие туры и услуги.",
      zh: "可靠的用户评价帮助您自信地选择最佳的旅游和服务。",
      ko: "신뢰할 수 있는 사용자 리뷰와 평점으로 최고의 투어와 서비스를 선택하세요.",
      pt: "Avaliações confiáveis de usuários ajudam você a escolher os melhores passeios e serviços com confiança.",
      ur: "مستند صارفین کے ریویوز اور ریٹنگز آپ کو بہترین ٹورز اور خدمات اعتماد سے منتخب کرنے میں مدد دیتے ہیں۔",
      ja: "信頼できるユーザーレビューが、最適なツアーやサービスを自信を持って選ぶ手助けをします。",
    },
  },
  {
    id: 7,
    icon: <FontAwesomeIcon icon={faMoneyBillWave} className="font-awesome" />,
    title: {
      ar: "عروض واضحة وأسعار منافسة",
      en: "Clear Offers & Competitive Prices",
      fr: "Offres claires et prix compétitifs",
      de: "Klare Angebote & Wettbewerbsfähige Preise",
      es: "Ofertas claras y precios competitivos",
      tr: "Şeffaf Teklifler ve Rekabetçi Fiyatlar",
      ru: "Прозрачные предложения и конкурентные цены",
      zh: "透明优惠和有竞争力的价格",
      ko: "투명한 혜택 및 경쟁력 있는 가격",
      pt: "Ofertas Claras e Preços Competitivos",
      ur: "واضح آفرز اور مسابقتی قیمتیں",
      ja: "明確なオファーと競争力のある価格",
    },
    text: {
      ar: "استمتع بخصومات وعروض حصرية مع شفافية كاملة للأسعار، لضمان أفضل قيمة مقابل كل تجربة تحجزها.",
      en: "Enjoy exclusive discounts and offers with full price transparency, ensuring the best value for every experience you book.",
      fr: "Profitez de réductions et offres exclusives avec une transparence totale des prix, garantissant la meilleure valeur pour chaque expérience.",
      de: "Genießen Sie exklusive Rabatte und Angebote mit voller Preistransparenz, um den besten Wert für jede Buchung zu erhalten.",
      es: "Disfruta de descuentos y ofertas exclusivas con total transparencia en los precios, asegurando el mejor valor en cada experiencia.",
      tr: "Tam fiyat şeffaflığıyla özel indirimler ve kampanyaların keyfini çıkarın; her deneyim için en iyi değeri garanti eder.",
      ru: "Наслаждайтесь эксклюзивными скидками и предложениями с полной прозрачностью цен, обеспечивая лучшую ценность каждой брони.",
      zh: "享受独家折扣和优惠，价格完全透明，确保每次预订的最佳价值。",
      ko: "완전한 가격 투명성과 함께 독점 할인과 혜택을 누리며 최고의 가치를 경험하세요.",
      pt: "Aproveite descontos e ofertas exclusivas com total transparência de preços, garantindo o melhor valor em cada reserva.",
      ur: "شفاف قیمتوں کے ساتھ خصوصی رعایتوں اور آفرز سے لطف اندوز ہوں تاکہ ہر تجربے میں بہترین قیمت حاصل ہو۔",
      ja: "価格の完全な透明性で限定割引とオファーを楽しみ、予約ごとに最高の価値を保証します。",
    },
  },
];
