const content = {
  bookNow: {
    en: "Book Now",
    ar: "احجز الآن",
    fr: "Réserver",
    de: "Jetzt buchen",
    es: "Reservar ahora",
    tr: "Şimdi Rezerv Et",
    ru: "Забронировать",
    zh: "立即预订",
    ko: "지금 예약",
    pt: "Reservar agora",
    ur: "اب بک کریں",
    ja: "今すぐ予約",
  },
  orderDetails: {
    en: "Order Details",
    ar: "تفاصيل الطلب",
    fr: "Détails de la commande",
    de: "Bestelldetails",
    es: "Detalles del pedido",
    tr: "Sipariş Detayları",
    ru: "Детали заказа",
    zh: "订单详情",
    ko: "주문 세부 정보",
    pt: "Detalhes do pedido",
    ur: "آرڈر کی تفصیلات",
    ja: "注文の詳細",
  },
  quantity: {
    en: "Quantity",
    ar: "الكمية",
    fr: "Quantité",
    de: "Menge",
    es: "Cantidad",
    tr: "Miktar",
    ru: "Количество",
    zh: "数量",
    ko: "수량",
    pt: "Quantidade",
    ur: "مقدار",
    ja: "数量",
  },
  deliveryMethod: {
    en: "Delivery Method",
    ar: "طريقة التوصيل",
    fr: "Mode de livraison",
    de: "Liefermethode",
    es: "Método de entrega",
    tr: "Teslimat Yöntemi",
    ru: "Способ доставки",
    zh: "配送方式",
    ko: "배송 방법",
    pt: "Método de entrega",
    ur: "ترسیل کا طریقہ",
    ja: "配送方法",
  },
  byMyself: {
    en: "By Myself",
    ar: "سأستلمها بنفسي",
    fr: "Par moi-même",
    de: "Selbst abholen",
    es: "Lo recogeré yo mismo",
    tr: "Kendim alacağım",
    ru: "Самовывоз",
    zh: "自取",
    ko: "직접 수령",
    pt: "Retirar pessoalmente",
    ur: "خود وصول کروں گا",
    ja: "自分で受け取る",
  },
  delivery: {
    en: "Delivery",
    ar: "التوصيل",
    fr: "Livraison",
    de: "Lieferung",
    es: "Entrega",
    tr: "Teslimat",
    ru: "Доставка",
    zh: "配送",
    ko: "배송",
    pt: "Entrega",
    ur: "ترسیل",
    ja: "配送",
  },
  address: {
    en: "Address",
    ar: "العنوان",
    fr: "Adresse",
    de: "Adresse",
    es: "Dirección",
    tr: "Adres",
    ru: "Адрес",
    zh: "地址",
    ko: "주소",
    pt: "Endereço",
    ur: "پتہ",
    ja: "住所",
  },
  phoneNumber: {
    en: "Phone Number",
    ar: "رقم الهاتف",
    fr: "Numéro de téléphone",
    de: "Telefonnummer",
    es: "Número de teléfono",
    tr: "Telefon Numarası",
    ru: "Номер телефона",
    zh: "电话号码",
    ko: "전화번호",
    pt: "Número de telefone",
    ur: "فون نمبر",
    ja: "電話番号",
  },
  submit: {
    en: "Starting Payment",
    ar: "بدأ الدفع",
    fr: "Commencer le paiement",
    de: "Zahlung starten",
    es: "Iniciar pago",
    tr: "Ödemeyi Başlat",
    ru: "Начать оплату",
    zh: "开始支付",
    ko: "결제 시작",
    pt: "Iniciar pagamento",
    ur: "ادائیگی شروع کریں",
    ja: "支払いを開始",
  },
  paymentInitiated: {
    en: "Payment initiated.",
    ar: "تم بدء عملية الدفع.",
    fr: "Paiement initié.",
    de: "Zahlung eingeleitet.",
    es: "Pago iniciado.",
    tr: "Ödeme başlatıldı.",
    ru: "Оплата начата.",
    zh: "支付已启动。",
    ko: "결제가 시작되었습니다.",
    pt: "Pagamento iniciado.",
    ur: "ادائیگی شروع ہوگئی ہے۔",
    ja: "支払いが開始されました。",
  },
  paymentFailed: {
    en: "Payment failed.",
    ar: "فشلت عملية الدفع.",
    fr: "Échec du paiement.",
    de: "Zahlung fehlgeschlagen.",
    es: "El pago ha fallado.",
    tr: "Ödeme başarısız oldu.",
    ru: "Оплата не прошла.",
    zh: "支付失败。",
    ko: "결제 실패.",
    pt: "Pagamento falhou.",
    ur: "ادائیگی ناکام ہوگئی۔",
    ja: "支払いに失敗しました。",
  },
  paymentSuccess: {
    en: "Payment successful.",
    ar: "تمت عملية الدفع بنجاح.",
    fr: "Paiement réussi.",
    de: "Zahlung erfolgreich.",
    es: "Pago exitoso.",
    tr: "Ödeme başarılı.",
    ru: "Оплата успешна.",
    zh: "支付成功。",
    ko: "결제 성공.",
    pt: "Pagamento bem-sucedido.",
    ur: "ادائیگی کامیاب رہی۔",
    ja: "支払い成功。",
  },
  paymentCancelled: {
    en: "Payment cancelled. Please try again.",
    ar: "تم الغاء عملية الدفع. يرجى المحاولة مرة أخرى.",
    fr: "Paiement annulé. Veuillez réessayer.",
    de: "Zahlung abgebrochen. Bitte erneut versuchen.",
    es: "Pago cancelado. Por favor, inténtelo de nuevo.",
    tr: "Ödeme iptal edildi. Lütfen tekrar deneyin.",
    ru: "Оплата отменена. Попробуйте снова.",
    zh: "支付已取消。请重试。",
    ko: "결제가 취소되었습니다. 다시 시도해주세요.",
    pt: "Pagamento cancelado. Por favor, tente novamente.",
    ur: "ادائیگی منسوخ ہوگئی۔ براہ کرم دوبارہ کوشش کریں۔",
    ja: "支払いがキャンセルされました。もう一度お試しください。",
  },
  choosePaymentWay: {
    en: "Payment Way",
    ar: "أختر طريقة الدفع",
    fr: "Mode de paiement",
    de: "Zahlungsmethode",
    es: "Forma de pago",
    tr: "Ödeme Yöntemi",
    ru: "Способ оплаты",
    zh: "支付方式",
    ko: "결제 방법",
    pt: "Forma de pagamento",
    ur: "ادائیگی کا طریقہ",
    ja: "支払い方法",
  },
  cash: {
    en: "Cash",
    ar: "نقدي",
    fr: "Espèces",
    de: "Barzahlung",
    es: "Efectivo",
    tr: "Nakit",
    ru: "Наличные",
    zh: "现金",
    ko: "현금",
    pt: "Dinheiro",
    ur: "نقد",
    ja: "現金",
  },
  online: {
    en: "Online",
    ar: "البطاقة البنكية",
    fr: "En ligne",
    de: "Online",
    es: "En línea",
    tr: "Online",
    ru: "Онлайн",
    zh: "在线",
    ko: "온라인",
    pt: "Online",
    ur: "آن لائن",
    ja: "オンライン",
  },
  country: {
    en: "Country",
    ar: "الدولة",
    fr: "Pays",
    de: "Land",
    es: "País",
    tr: "Ülke",
    ru: "Страна",
    zh: "国家",
    ko: "국가",
    pt: "País",
    ur: "ملک",
    ja: "国",
  },
  city: {
    en: "City",
    ar: "المدينة",
    fr: "Ville",
    de: "Stadt",
    es: "Ciudad",
    tr: "Şehir",
    ru: "Город",
    zh: "城市",
    ko: "도시",
    pt: "Cidade",
    ur: "شہر",
    ja: "市",
  },
  selectCountry: {
    en: "Select Country",
    ar: "اختر الدولة",
    fr: "Sélectionner un pays",
    de: "Land auswählen",
    es: "Seleccionar país",
    tr: "Ülke seçin",
    ru: "Выберите страну",
    zh: "选择国家",
    ko: "국가 선택",
    pt: "Selecionar país",
    ur: "ملک منتخب کریں",
    ja: "国を選択",
  },
  selectCity: {
    en: "Select City",
    ar: "اختر المدينة",
    fr: "Sélectionner une ville",
    de: "Stadt auswählen",
    es: "Seleccionar ciudad",
    tr: "Şehir seçin",
    ru: "Выберите город",
    zh: "选择城市",
    ko: "도시 선택",
    pt: "Selecionar cidade",
    ur: "شہر منتخب کریں",
    ja: "市を選択",
  },
  deliveryCost: {
    en: "Delivery Cost",
    ar: "تكلفة التوصيل",
    fr: "Frais de livraison",
    de: "Lieferkosten",
    es: "Costo de entrega",
    tr: "Teslimat Ücreti",
    ru: "Стоимость доставки",
    zh: "运费",
    ko: "배송비",
    pt: "Custo de entrega",
    ur: "ترسیل کی لاگت",
    ja: "配送料",
  },
  errors: {
    missingFields: {
      en: "Please enter address, phone number, country, and city",
      ar: "الرجاء إدخال العنوان ورقم الهاتف والدولة والمدينة",
      fr: "Veuillez entrer l'adresse, le numéro de téléphone, le pays et la ville",
      de: "Bitte Adresse, Telefonnummer, Land und Stadt eingeben",
      es: "Por favor ingrese la dirección, el número de teléfono, el país y la ciudad",
      tr: "Lütfen adres, telefon numarası, ülke ve şehir giriniz",
      ru: "Пожалуйста, введите адрес, номер телефона, страну и город",
      zh: "请输入地址、电话号码、国家和城市",
      ko: "주소, 전화번호, 국가 및 도시를 입력하세요",
      pt: "Por favor, insira endereço, número de telefone, país e cidade",
      ur: "براہ کرم پتہ، فون نمبر، ملک اور شہر درج کریں",
      ja: "住所、電話番号、国、市を入力してください",
    },
  },
  processing: {
    en: "Processing...",
    ar: "جاري المعالجة...",
    fr: "Traitement en cours...",
    de: "Wird bearbeitet...",
    es: "Procesando...",
    tr: "İşleniyor...",
    ru: "Обработка...",
    zh: "处理中...",
    ko: "처리 중...",
    pt: "Processando...",
    ur: "پراسسنگ ہو رہی ہے...",
    ja: "処理中...",
  },
};

export default content;
