export const content = {
  en: {
    selectDate: "Select a trip date",
    numberOfPeople: "Number of people",
    people: "people",
    showPrograms: "Show available programs",
    freeCancel: "Free cancellation",
    payLater: "Pay later",
    pleaseLogin: "Please login to continue",
  },
  ar: {
    selectDate: "حدد تاريخ الرحلة",
    numberOfPeople: "عدد الأفراد",
    people: "افراد",
    showPrograms: "إظهر البرامج المتاحة",
    freeCancel: "إلغاء الحجز مجانا",
    payLater: "إدفع لاحقا",
    pleaseLogin: "الرجاء تسجيل الدخول للمتابعة",
  },
  fr: {
    selectDate: "Sélectionnez une date de voyage",
    numberOfPeople: "Nombre de personnes",
    people: "personnes",
    showPrograms: "Afficher les programmes disponibles",
    freeCancel: "Annulation gratuite",
    payLater: "Payer plus tard",
    pleaseLogin: "Veuillez vous connecter pour continuer",
  },
  de: {
    selectDate: "Wählen Sie ein Reisedatum",
    numberOfPeople: "Anzahl der Personen",
    people: "Personen",
    showPrograms: "Verfügbare Programme anzeigen",
    freeCancel: "Kostenlose Stornierung",
    payLater: "Später bezahlen",
    pleaseLogin: "Bitte melden Sie sich an, um fortzufahren",
  },
  es: {
    selectDate: "Seleccione una fecha de viaje",
    numberOfPeople: "Número de personas",
    people: "personas",
    showPrograms: "Mostrar programas disponibles",
    freeCancel: "Cancelación gratuita",
    payLater: "Pagar más tarde",
    pleaseLogin: "Por favor inicie sesión para continuar",
  },
  tr: {
    selectDate: "Seyahat tarihi seçin",
    numberOfPeople: "Kişi sayısı",
    people: "kişi",
    showPrograms: "Mevcut programları göster",
    freeCancel: "Ücretsiz iptal",
    payLater: "Sonra öde",
    pleaseLogin: "Devam etmek için lütfen giriş yapın",
  },
  ru: {
    selectDate: "Выберите дату поездки",
    numberOfPeople: "Количество человек",
    people: "человек",
    showPrograms: "Показать доступные программы",
    freeCancel: "Бесплатная отмена",
    payLater: "Оплатить позже",
    pleaseLogin: "Пожалуйста, войдите, чтобы продолжить",
  },
  zh: {
    selectDate: "选择旅行日期",
    numberOfPeople: "人数",
    people: "人",
    showPrograms: "显示可用的行程",
    freeCancel: "免费取消",
    payLater: "稍后付款",
    pleaseLogin: "请登录以继续",
  },
  ko: {
    selectDate: "여행 날짜를 선택하세요",
    numberOfPeople: "인원수",
    people: "명",
    showPrograms: "이용 가능한 프로그램 보기",
    freeCancel: "무료 취소",
    payLater: "나중에 결제",
    pleaseLogin: "계속하려면 로그인하세요",
  },
  pt: {
    selectDate: "Selecione uma data da viagem",
    numberOfPeople: "Número de pessoas",
    people: "pessoas",
    showPrograms: "Mostrar programas disponíveis",
    freeCancel: "Cancelamento gratuito",
    payLater: "Pagar depois",
    pleaseLogin: "Por favor, faça login para continuar",
  },
  ur: {
    selectDate: "سفر کی تاریخ منتخب کریں",
    numberOfPeople: "افراد کی تعداد",
    people: "افراد",
    showPrograms: "دستیاب پروگرام دکھائیں",
    freeCancel: "مفت منسوخی",
    payLater: "بعد میں ادائیگی کریں",
    pleaseLogin: "جاری رکھنے کے لیے براہ کرم لاگ ان کریں",
  },
  ja: {
    selectDate: "旅行日を選択してください",
    numberOfPeople: "人数",
    people: "人",
    showPrograms: "利用可能なプログラムを表示",
    freeCancel: "無料キャンセル",
    payLater: "後で支払う",
    pleaseLogin: "続行するにはログインしてください",
  },
};
