const boxTranslations = {
  available: {
    ar: "متاح",
    en: "Available",
    fr: "Disponible",
    de: "Verfügbar",
    es: "Disponible",
    tr: "Mevcut",
    ru: "Доступно",
    zh: "可用",
    ko: "사용 가능",
    pt: "Disponível",
    ur: "دستیاب",
    ja: "利用可能",
  },
  unavailable: {
    ar: "غير متاح",
    en: "Unavailable",
    fr: "Indisponible",
    de: "Nicht verfügbar",
    es: "No disponible",
    tr: "Mevcut değil",
    ru: "Недоступно",
    zh: "不可用",
    ko: "사용 불가",
    pt: "Indisponível",
    ur: "دستیاب نہیں",
    ja: "利用不可",
  },
  programTime: {
    ar: "وقت البرنامج",
    en: "Program time",
    fr: "Heure du programme",
    de: "Programmzeit",
    es: "Hora del programa",
    tr: "Program zamanı",
    ru: "Время программы",
    zh: "节目时间",
    ko: "프로그램 시간",
    pt: "Hora do programa",
    ur: "پروگرام کا وقت",
    ja: "プログラム時間",
  },
  guideLanguages: {
    ar: "لغات الإرشاد",
    en: "Guide Languages",
    fr: "Langues de guide",
    de: "Führersprachen",
    es: "Idiomas del guía",
    tr: "Rehber Dilleri",
    ru: "Языки гида",
    zh: "导游语言",
    ko: "가이드 언어",
    pt: "Idiomas do guia",
    ur: "رہنما کی زبانیں",
    ja: "ガイドの言語",
    sgn: "Sign Language", // لغة الإشارة
  },
  minBooking: {
    ar: "الحد الأدنى للحجز",
    en: "Minimum booking",
    fr: "Réservation minimale",
    de: "Mindestbuchung",
    es: "Reserva mínima",
    tr: "Minimum rezervasyon",
    ru: "Минимальное бронирование",
    zh: "最少预订",
    ko: "최소 예약",
    pt: "Reserva mínima",
    ur: "کم سے کم بکنگ",
    ja: "最小予約数",
  },
  maxBooking: {
    ar: "الحد الأقصى للحجز",
    en: "Maximum booking",
    fr: "Réservation maximale",
    de: "Maximale Buchung",
    es: "Reserva máxima",
    tr: "Maksimum rezervasyon",
    ru: "Максимальное бронирование",
    zh: "最大预订",
    ko: "최대 예약",
    pt: "Reserva máxima",
    ur: "زیادہ سے زیادہ بکنگ",
    ja: "最大予約数",
  },
  group: {
    ar: "مجموعة",
    en: "Group",
    fr: "Groupe",
    de: "Gruppe",
    es: "Grupo",
    tr: "Grup",
    ru: "Группа",
    zh: "团体",
    ko: "그룹",
    pt: "Grupo",
    ur: "گروپ",
    ja: "グループ",
  },
  individual: {
    ar: "فردي",
    en: "Individual",
    fr: "Individuel",
    de: "Individuell",
    es: "Individual",
    tr: "Bireysel",
    ru: "Индивидуальный",
    zh: "个人",
    ko: "개인",
    pt: "Individual",
    ur: "انفرادی",
    ja: "個人",
  },
  activityEndTime: {
    ar: "وقت نهاية الفعالية",
    en: "Activity End Time",
    fr: "Heure de fin de l'activité",
    de: "Aktivitätsendzeit",
    es: "Hora de finalización de la actividad",
    tr: "Etkinlik Bitiş Zamanı",
    ru: "Время окончания мероприятия",
    zh: "活动结束时间",
    ko: "활동 종료 시간",
    pt: "Hora de término da atividade",
    ur: "سرگرمی کے اختتام کا وقت",
    ja: "アクティビティ終了時間"
  },
};
export default boxTranslations;
