// translations.js
export const eventTranslations = {
  perGroup: {
    ar: "للمجموعة",
    en: "Per Group",
    fr: "Par groupe",
    de: "Pro Gruppe",
    es: "Por grupo",
    tr: "Grup başına",
    ru: "За группу",
    zh: "每组",
    ko: "그룹당",
    pt: "Por grupo",
    ur: "گروپ کے لیے",
    ja: "グループごと",
  },
  perPerson: {
    ar: "للفرد",
    en: "Per Person",
    fr: "Par personne",
    de: "Pro Person",
    es: "Por persona",
    tr: "Kişi başı",
    ru: "За человека",
    zh: "每人",
    ko: "1인당",
    pt: "Por pessoa",
    ur: "فی فرد",
    ja: "1人あたり",
  },
  reserve: {
    ar: "حجز",
    en: "Reserve",
    fr: "Réserver",
    de: "Reservieren",
    es: "Reservar",
    tr: "Rezervasyon",
    ru: "Забронировать",
    zh: "预订",
    ko: "예약",
    pt: "Reservar",
    ur: "بک کریں",
    ja: "予約する",
  },
};
export default eventTranslations;
