const finalContent = {
  validation: {
    email: {
      en: "Invalid email address",
      ar: "عنوان بريد إلكتروني غير صالح",
      fr: "Adresse e-mail invalide",
      es: "Dirección de correo electrónico no válida",
      de: "Ungültige E-Mail-Adresse",
      zh: "无效的电子邮件地址",
      ru: "Неверный адрес электронной почты",
      ja: "無効なメールアドレス",
      pt: "Endereço de e-mail inválido",
      it: "Indirizzo email non valido",
      ko: "유효하지 않은 이메일 주소",
      nl: "Ongeldig e-mailadres",
    },
    emailRequired: {
      en: "Email is required",
      ar: "البريد الإلكتروني مطلوب",
      fr: "L'e-mail est requis",
      es: "El correo electrónico es obligatorio",
      de: "E-Mail ist erforderlich",
      zh: "电子邮件是必需的",
      ru: "Электронная почта обязательна",
      ja: "メールアドレスは必須です",
      pt: "O e-mail é obrigatório",
      it: "L'email è richiesta",
      ko: "이메일은 필수입니다",
      nl: "E-mail is verplicht",
    },
    nameRequired: {
      en: "Name is required",
      ar: "الاسم مطلوب",
      fr: "Le nom est requis",
      es: "El nombre es obligatorio",
      de: "Name ist erforderlich",
      zh: "姓名是必需的",
      ru: "Имя обязательно",
      ja: "名前は必須です",
      pt: "O nome é obrigatório",
      it: "Il nome è richiesto",
      ko: "이름은 필수입니다",
      nl: "Naam is verplicht",
    },
    phoneInvalid: {
      en: "Phone number is not valid",
      ar: "رقم الهاتف غير صالح",
      fr: "Le numéro de téléphone n'est pas valide",
      es: "El número de teléfono no es válido",
      de: "Telefonnummer ist ungültig",
      zh: "电话号码无效",
      ru: "Номер телефона недействителен",
      ja: "電話番号が無効です",
      pt: "Número de telefone inválido",
      it: "Numero di telefono non valido",
      ko: "전화번호가 유효하지 않습니다",
      nl: "Telefoonnummer is ongeldig",
    },
    phoneRequired: {
      en: "Phone number is required",
      ar: "رقم الهاتف مطلوب",
      fr: "Le numéro de téléphone est requis",
      es: "El número de teléfono es obligatorio",
      de: "Telefonnummer ist erforderlich",
      zh: "电话号码是必需的",
      ru: "Номер телефона обязателен",
      ja: "電話番号は必須です",
      pt: "O número de telefone é obrigatório",
      it: "Il numero di telefono è richiesto",
      ko: "전화번호는 필수입니다",
      nl: "Telefoonnummer is verplicht",
    },
    passwordMin: {
      en: "Password must be at least 8 characters",
      ar: "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
      fr: "Le mot de passe doit contenir au moins 8 caractères",
      es: "La contraseña debe tener al menos 8 caracteres",
      de: "Das Passwort muss mindestens 8 Zeichen lang sein",
      zh: "密码必须至少8个字符",
      ru: "Пароль должен содержать не менее 8 символов",
      ja: "パスワードは8文字以上である必要があります",
      pt: "A senha deve ter pelo menos 8 caracteres",
      it: "La password deve contenere almeno 8 caratteri",
      ko: "비밀번호는 8자 이상이어야 합니다",
      nl: "Wachtwoord moet minimaal 8 tekens lang zijn",
    },
    passwordRequired: {
      en: "Password is required",
      ar: "كلمة المرور مطلوبة",
      fr: "Le mot de passe est requis",
      es: "La contraseña es obligatoria",
      de: "Passwort ist erforderlich",
      zh: "密码是必需的",
      ru: "Пароль обязателен",
      ja: "パスワードは必須です",
      pt: "A senha é obrigatória",
      it: "La password è richiesta",
      ko: "비밀번호는 필수입니다",
      nl: "Wachtwoord is verplicht",
    },
    passwordConfirmMatch: {
      en: "Passwords must match",
      ar: "يجب أن تتطابق كلمات المرور",
      fr: "Les mots de passe doivent correspondre",
      es: "Las contraseñas deben coincidir",
      de: "Passwörter müssen übereinstimmen",
      zh: "密码必须匹配",
      ru: "Пароли должны совпадать",
      ja: "パスワードが一致しません",
      pt: "As senhas devem corresponder",
      it: "Le password devono corrispondere",
      ko: "비밀번호가 일치해야 합니다",
      nl: "Wachtwoorden moeten overeenkomen",
    },
    passwordConfirmRequired: {
      en: "Password confirmation is required",
      ar: "تأكيد كلمة المرور مطلوب",
      fr: "La confirmation du mot de passe est requise",
      es: "La confirmación de la contraseña es obligatoria",
      de: "Passwortbestätigung ist erforderlich",
      zh: "需要确认密码",
      ru: "Подтверждение пароля обязательно",
      ja: "パスワードの確認は必須です",
      pt: "A confirmação da senha é obrigatória",
      it: "La conferma della password è richiesta",
      ko: "비밀번호 확인은 필수입니다",
      nl: "Wachtwoordbevestiging is verplicht",
    },
  },
  title: {
    en: "Final Registration",
    ar: "التسجيل النهائي",
    fr: "Inscription finale",
    es: "Registro final",
    de: "Endgültige Registrierung",
    zh: "最终注册",
    ru: "Окончательная регистрация",
    ja: "最終登録",
    pt: "Registro final",
    it: "Registrazione finale",
    ko: "최종 등록",
    nl: "Definitieve registratie",
  },
  email: {
    en: "Email",
    ar: "البريد الإلكتروني",
    fr: "E-mail",
    es: "Correo electrónico",
    de: "E-Mail",
    zh: "电子邮件",
    ru: "Эл. почта",
    ja: "Eメール",
    pt: "E-mail",
    it: "E-mail",
    ko: "이메일",
    nl: "E-mail",
  },
  name: {
    en: "Name",
    ar: "الاسم",
    fr: "Nom",
    es: "Nombre",
    de: "Name",
    zh: "姓名",
    ru: "Имя",
    ja: "名前",
    pt: "Nome",
    it: "Nome",
    ko: "이름",
    nl: "Naam",
  },
  phone: {
    en: "Phone",
    ar: "الهاتف",
    fr: "Téléphone",
    es: "Teléfono",
    de: "Telefon",
    zh: "电话",
    ru: "Телефон",
    ja: "電話",
    pt: "Telefone",
    it: "Telefono",
    ko: "전화",
    nl: "Telefoon",
  },
  password: {
    en: "Password",
    ar: "كلمة المرور",
    fr: "Mot de passe",
    es: "Contraseña",
    de: "Passwort",
    zh: "密码",
    ru: "Пароль",
    ja: "パスワード",
    pt: "Senha",
    it: "Password",
    ko: "비밀번호",
    nl: "Wachtwoord",
  },
  passwordConfirm: {
    en: "Confirm Password",
    ar: "تأكيد كلمة المرور",
    fr: "Confirmer le mot de passe",
    es: "Confirmar contraseña",
    de: "Passwort bestätigen",
    zh: "确认密码",
    ru: "Подтвердить пароль",
    ja: "パスワードの確認",
    pt: "Confirmar senha",
    it: "Conferma password",
    ko: "비밀번호 확인",
    nl: "Wachtwoord bevestigen",
  },
  submit: {
    en: "Submit",
    ar: "إرسال",
    fr: "Soumettre",
    es: "Enviar",
    de: "Senden",
    zh: "提交",
    ru: "Отправить",
    ja: "送信",
    pt: "Enviar",
    it: "Invia",
    ko: "제출",
    nl: "Verzenden",
  },
  alreadyHaveAccount: {
    en: "Already have an account?",
    ar: "هل لديك حساب بالفعل؟",
    fr: "Vous avez déjà un compte ?",
    es: "¿Ya tienes una cuenta?",
    de: "Haben Sie bereits ein Konto?",
    zh: "已有账户？",
    ru: "Уже есть аккаунт?",
    ja: "すでにアカウントをお持ちですか？",
    pt: "Já tem uma conta?",
    it: "Hai già un account?",
    ko: "이미 계정이 있으신가요?",
    nl: "Heb je al een account?",
  },
  login: {
    en: "Login",
    ar: "تسجيل الدخول",
    fr: "Connexion",
    es: "Iniciar sesión",
    de: "Anmelden",
    zh: "登录",
    ru: "Войти",
    ja: "ログイン",
    pt: "Entrar",
    it: "Accedi",
    ko: "로그인",
    nl: "Inloggen",
  },
};

export default finalContent;