// 📝 translations
const content = {
  ar: {
    slogan: "اكتشف أكثر .. مع جولة",
    hi: "مرحبًا",
    cityNotAvailable: "هذه المدينة غير متاحة لدينا حاليا",
    cityDetailsNotAvailable: "تفاصيل المدينة غير متاحة",
    loginToSearch: "يرجى تسجيل الدخول للبحث",
    cityNotSupported: "هذه المدينة غير متاحة لدينا حاليا",
  },
  en: {
    slogan: "Explore more .. with ATOUR",
    hi: "Hi",
    cityNotAvailable: "This city is not supported yet.",
    cityDetailsNotAvailable: "City details not available",
    loginToSearch: "Please login to search",
    cityNotSupported: "This city is not supported yet.",
  },
  fr: {
    slogan: "Découvrez plus .. avec ATOUR",
    hi: "Salut",
    cityNotAvailable: "Cette ville n'est pas encore disponible.",
    cityDetailsNotAvailable: "Détails de la ville non disponibles",
    loginToSearch: "Veuillez vous connecter pour rechercher",
    cityNotSupported: "Cette ville n'est pas encore disponible.",
  },
  de: {
    slogan: "Entdecken Sie mehr .. mit ATOUR",
    hi: "Hallo",
    cityNotAvailable: "Diese Stadt wird noch nicht unterstützt.",
    cityDetailsNotAvailable: "Stadtdetails nicht verfügbar",
    loginToSearch: "Bitte melden Sie sich an, um zu suchen",
    cityNotSupported: "Diese Stadt wird noch nicht unterstützt.",
  },
  es: {
    slogan: "Descubre más .. con ATOUR",
    hi: "Hola",
    cityNotAvailable: "Esta ciudad aún no está disponible.",
    cityDetailsNotAvailable: "Detalles de la ciudad no disponibles",
    loginToSearch: "Por favor inicia sesión para buscar",
    cityNotSupported: "Esta ciudad aún no está disponible.",
  },
  tr: {
    slogan: "Daha fazlasını keşfet .. ATOUR ile",
    hi: "Merhaba",
    cityNotAvailable: "Bu şehir henüz mevcut değil.",
    cityDetailsNotAvailable: "Şehir detayları mevcut değil",
    loginToSearch: "Arama yapmak için lütfen giriş yapın",
    cityNotSupported: "Bu şehir henüz mevcut değil.",
  },
  ru: {
    slogan: "Откройте больше .. с ATOUR",
    hi: "Привет",
    cityNotAvailable: "Этот город пока недоступен.",
    cityDetailsNotAvailable: "Детали города недоступны",
    loginToSearch: "Пожалуйста, войдите, чтобы выполнить поиск",
    cityNotSupported: "Этот город пока недоступен.",
  },
  zh: {
    slogan: "探索更多 .. 与ATOUR一起",
    hi: "你好",
    cityNotAvailable: "该城市暂不支持。",
    cityDetailsNotAvailable: "城市详情不可用",
    loginToSearch: "请登录后再搜索",
    cityNotSupported: "该城市暂不支持。",
  },
  ko: {
    slogan: "더 많이 발견하세요 .. ATOUR와 함께",
    hi: "안녕하세요",
    cityNotAvailable: "이 도시는 아직 지원되지 않습니다.",
    cityDetailsNotAvailable: "도시 세부정보를 사용할 수 없습니다",
    loginToSearch: "검색하려면 로그인하세요",
    cityNotSupported: "이 도시는 아직 지원되지 않습니다.",
  },
  pt: {
    slogan: "Descubra mais .. com a ATOUR",
    hi: "Olá",
    cityNotAvailable: "Esta cidade ainda não está disponível.",
    cityDetailsNotAvailable: "Detalhes da cidade não disponíveis",
    loginToSearch: "Por favor, faça login para pesquisar",
    cityNotSupported: "Esta cidade ainda não está disponível.",
  },
  ur: {
    slogan: "مزید دریافت کریں .. ATOUR کے ساتھ",
    hi: "ہیلو",
    cityNotAvailable: "یہ شہر فی الحال دستیاب نہیں ہے۔",
    cityDetailsNotAvailable: "شہر کی تفصیلات دستیاب نہیں ہیں",
    loginToSearch: "براہ کرم تلاش کرنے کے لیے لاگ ان کریں",
    cityNotSupported: "یہ شہر فی الحال دستیاب نہیں ہے۔",
  },
  ja: {
    slogan: "さらに発見 .. ATOURで",
    hi: "こんにちは",
    cityNotAvailable: "この都市はまだサポートされていません。",
    cityDetailsNotAvailable: "都市の詳細は利用できません",
    loginToSearch: "検索するにはログインしてください",
    cityNotSupported: "この都市はまだサポートされていません。",
  },
};
export default content;
