const loginContent = {
    title: {
        ar: "تسجيل الدخول",
        en: "Login",
        fr: "Connexion",
        de: "Anmelden",
        es: "Iniciar sesión",
        it: "Accesso",
        pt: "Conecte-se",
        ru: "Авторизоваться",
        ja: "ログイン",
        zh: "登录",
        ko: "로그인",
        hi: "लॉग इन करें",
    },
    loading: {
        ar: "جار التحميل...",
        en: "Loading...",
        fr: "Chargement...",
        de: "Wird geladen...",
        es: "Cargando...",
        tr: "Yükleniyor...",
        ru: "Загрузка...",
        zh: "加载中...",
        ko: "로드 중...",
        pt: "Carregando...",
        ur: "لوڈ ہو رہا ہے...",
        ja: "読み込み中...",
    },
    emailOrPhoneLabel: {
        ar: "البريد الإلكتروني أو رقم الهاتف",
        en: "Email or Phone Number",
        fr: "E-mail ou numéro de téléphone",
        de: "E-Mail oder Telefonnummer",
        es: "Correo electrónico o número de teléfono",
        it: "Email o numero di telefono",
        pt: "E-mail ou número de telefone",
        ru: "Электронная почта или номер телефона",
        ja: "メールアドレスまたは電話番号",
        zh: "电子邮件或电话号码",
        ko: "이메일 또는 전화번호",
        hi: "ईमेल या फ़ोन नंबर",
    },
    emailOrPhonePlaceholder: {
        ar: "أدخل البريد الإلكتروني أو رقم الهاتف",
        en: "Enter your email or phone number",
        fr: "Entrez votre e-mail ou numéro de téléphone",
        de: "Geben Sie Ihre E-Mail-Adresse oder Telefonnummer ein",
        es: "Ingrese su correo electrónico o número de teléfono",
        it: "Inserisci la tua email o numero di telefono",
        pt: "Digite seu e-mail ou número de telefone",
        ru: "Введите свой адрес электронной почты или номер телефона",
        ja: "メールアドレスまたは電話番号を入力してください",
        zh: "输入您的电子邮件或电话号码",
        ko: "이메일 또는 전화번호를 입력하세요",
        hi: "अपना ईमेल या फ़ोन नंबर दर्ज करें",
    },
    passwordLabel: {
        ar: "كلمة المرور",
        en: "Password",
        fr: "Mot de passe",
        de: "Passwort",
        es: "Contraseña",
        it: "Password",
        pt: "Senha",
        ru: "Пароль",
        ja: "パスワード",
        zh: "密码",
        ko: "비밀번호",
        hi: "पासवर्ड",
    },
    passwordPlaceholder: {
        ar: "أدخل كلمة المرور",
        en: "Enter your password",
        fr: "Entrez votre mot de passe",
        de: "Geben Sie Ihr Passwort ein",
        es: "Ingrese su contraseña",
        it: "Inserisci la tua password",
        pt: "Digite sua senha",
        ru: "Введите свой пароль",
        ja: "パスワードを入力してください",
        zh: "输入您的密码",
        ko: "비밀번호를 입력하세요",
        hi: "अपना पासवर्ड दर्ज करें",
    },
    submitButton: {
        ar: "تسجيل الدخول",
        en: "Login",
        fr: "Connexion",
        de: "Anmelden",
        es: "Iniciar sesión",
        it: "Accesso",
        pt: "Conecte-se",
        ru: "Авторизоваться",
        ja: "ログイン",
        zh: "登录",
        ko: "로그인",
        hi: "लॉग इन करें",
    },
    noAccount: {
        ar: "ليس لديك حساب؟",
        en: "Don't have an account?",
        fr: "Vous n'avez pas de compte ?",
        de: "Sie haben kein Konto?",
        es: "¿No tienes una cuenta?",
        it: "Non hai un account?",
        pt: "Não tem uma conta?",
        ru: "Нет аккаунта?",
        ja: "アカウントをお持ちではありませんか？",
        zh: "没有帐户？",
        ko: "계정이 없으신가요?",
        hi: "खाता नहीं है?",
    },
    registerLink: {
        ar: "سجل الآن",
        en: "Register Now",
        fr: "Inscrivez-vous maintenant",
        de: "Jetzt registrieren",
        es: "Regístrate ahora",
        it: "Registrati ora",
        pt: "Registre-se agora",
        ru: "Зарегистрироваться сейчас",
        ja: "今すぐ登録",
        zh: "立即注册",
        ko: "지금 등록하세요",
        hi: "अभी पंजीकरण करें",
    },
    forgetPassword: {
        ar: "هل نسيت كلمة المرور؟",
        en: "Forgot Password?",
        fr: "Mot de passe oublié ?",
        de: "Passwort vergessen?",
        es: "¿Olvidaste tu contraseña?",
        it: "Password dimenticata?",
        pt: "Esqueceu a senha?",
        ru: "Забыли пароль?",
        ja: "パスワードをお忘れですか？",
        zh: "忘记密码？",
        ko: "비밀번호를 잊으셨나요?",
        hi: "पासवर्ड भूल गए?",
    },
    validation: {
        emailOrPhoneRequired: {
            ar: "ادخل البريد الإلكتروني أو رقم الهاتف",
            en: "Enter your email or phone number",
            fr: "Entrez votre e-mail ou numéro de téléphone",
            de: "Geben Sie Ihre E-Mail-Adresse oder Telefonnummer ein",
            es: "Ingrese su correo electrónico o número de teléfono",
            it: "Inserisci la tua email o numero di telefono",
            pt: "Digite seu e-mail ou número de telefone",
            ru: "Введите свой адрес электронной почты или номер телефона",
            ja: "メールアドレスまたは電話番号を入力してください",
            zh: "输入您的电子邮件或电话号码",
            ko: "이메일 또는 전화번호를 입력하세요",
            hi: "अपना ईमेल या फ़ोन नंबर दर्ज करें",
        },
        emailOrPhoneInvalid: {
            ar: "رقم هاتف أو بريد إلكتروني غير صحيح",
            en: "Invalid email or phone number",
            fr: "E-mail ou numéro de téléphone invalide",
            de: "Ungültige E-Mail-Adresse oder Telefonnummer",
            es: "Correo electrónico o número de teléfono no válido",
            it: "Email o numero di telefono non valido",
            pt: "E-mail ou número de telefone inválido",
            ru: "Неверный адрес электронной почты или номер телефона",
            ja: "無効なメールアドレスまたは電話番号",
            zh: "无效的电子邮件或电话号码",
            ko: "유효하지 않은 이메일 또는 전화번호",
            hi: "अमान्य ईमेल या फ़ोन नंबर",
        },
        phoneInvalid: {
            ar: "رقم هاتف غير صحيح",
            en: "Invalid phone number",
            fr: "Numéro de téléphone invalide",
            de: "Ungültige Telefonnummer",
            es: "Número de teléfono no válido",
            it: "Numero di telefono non valido",
            pt: "Número de telefone inválido",
            ru: "Неверный номер телефона",
            ja: "無効な電話番号",
            zh: "无效电话号码",
            ko: "유효하지 않은 전화번호",
            hi: "अमान्य फ़ोन नंबर",
        },
        passwordMinLength: {
            ar: "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل",
            en: "Password must be at least 6 characters",
            fr: "Le mot de passe doit contenir au moins 6 caractères",
            de: "Das Passwort muss mindestens 6 Zeichen lang sein",
            es: "La contraseña debe tener al menos 6 caracteres",
            it: "La password deve contenere almeno 6 caratteri",
            pt: "A senha deve ter pelo menos 6 caracteres",
            ru: "Пароль должен содержать не менее 6 символов",
            ja: "パスワードは6文字以上である必要があります",
            zh: "密码必须至少包含6个字符",
            ko: "비밀번호는 6자 이상이어야 합니다",
            hi: "पासवर्ड कम से कम 6 वर्णों का होना चाहिए",
        },
        passwordRequired: {
            ar: "ادخل كلمة المرور",
            en: "Enter your password",
            fr: "Entrez votre mot de passe",
            de: "Geben Sie Ihr Passwort ein",
            es: "Ingrese su contraseña",
            it: "Inserisci la tua password",
            pt: "Digite sua senha",
            ru: "Введите свой пароль",
            ja: "パスワードを入力してください",
            zh: "输入您的密码",
            ko: "비밀번호를 입력하세요",
            hi: "अपना पासवर्ड दर्ज करें",
        },
    },
};

export default loginContent;