const biographyContent = {
  ar: {
    cityNotAvailable: "هذه المدينة غير متاحة",
    home: "الصفحة الرئيسية",
    cityDetailsNotAvailable: "تفاصيل المدينة غير متاحة",
    introduction: "نبذة تعريفية",
    biographyNotFound: "السيرة غير متاحة.",
    failedToLoad: "فشل في تحميل بيانات السيرة. حاول مرة أخرى لاحقاً.",
  },
  en: {
    cityNotAvailable: "This city is not available",
    home: "Home",
    cityDetailsNotAvailable: "City details not available",
    introduction: "Introduction",
    biographyNotFound: "Biography not found.",
    failedToLoad: "Failed to load biography data. Please try again later.",
  },
  fr: {
    cityNotAvailable: "Cette ville n'est pas disponible",
    home: "Accueil",
    cityDetailsNotAvailable: "Détails de la ville non disponibles",
    introduction: "Introduction",
    biographyNotFound: "Biographie non trouvée.",
    failedToLoad: "Échec du chargement des données de la biographie. Veuillez réessayer plus tard.",
  },
  de: {
    cityNotAvailable: "Diese Stadt ist nicht verfügbar",
    home: "Startseite",
    cityDetailsNotAvailable: "Stadtdetails nicht verfügbar",
    introduction: "Einführung",
    biographyNotFound: "Biografie nicht gefunden.",
    failedToLoad: "Biografie-Daten konnten nicht geladen werden. Bitte versuchen Sie es später erneut.",
  },
  es: {
    cityNotAvailable: "Esta ciudad no está disponible",
    home: "Inicio",
    cityDetailsNotAvailable: "Detalles de la ciudad no disponibles",
    introduction: "Introducción",
    biographyNotFound: "Biografía no encontrada.",
    failedToLoad: "No se pudieron cargar los datos de la biografía. Por favor, inténtelo de nuevo más tarde.",
  },
  tr: {
    cityNotAvailable: "Bu şehir mevcut değil",
    home: "Ana Sayfa",
    cityDetailsNotAvailable: "Şehir detayları mevcut değil",
    introduction: "Giriş",
    biographyNotFound: "Biyografi bulunamadı.",
    failedToLoad: "Biyografi verileri yüklenemedi. Lütfen daha sonra tekrar deneyin.",
  },
  ru: {
    cityNotAvailable: "Этот город недоступен",
    home: "Главная",
    cityDetailsNotAvailable: "Детали города недоступны",
    introduction: "Введение",
    biographyNotFound: "Биография не найдена.",
    failedToLoad: "Не удалось загрузить данные биографии. Пожалуйста, попробуйте позже.",
  },
  zh: {
    cityNotAvailable: "该城市不可用",
    home: "首页",
    cityDetailsNotAvailable: "城市详情不可用",
    introduction: "简介",
    biographyNotFound: "未找到简介。",
    failedToLoad: "加载简介数据失败，请稍后再试。",
  },
  ko: {
    cityNotAvailable: "이 도시는 사용할 수 없습니다",
    home: "홈",
    cityDetailsNotAvailable: "도시 세부 정보가 제공되지 않습니다",
    introduction: "소개",
    biographyNotFound: "전기를 찾을 수 없습니다.",
    failedToLoad: "전기 데이터를 불러오지 못했습니다. 나중에 다시 시도해주세요.",
  },
  pt: {
    cityNotAvailable: "Esta cidade não está disponível",
    home: "Início",
    cityDetailsNotAvailable: "Detalhes da cidade não disponíveis",
    introduction: "Introdução",
    biographyNotFound: "Biografia não encontrada.",
    failedToLoad: "Falha ao carregar os dados da biografia. Por favor, tente novamente mais tarde.",
  },
  ur: {
    cityNotAvailable: "یہ شہر دستیاب نہیں ہے",
    home: "ہوم",
    cityDetailsNotAvailable: "شہر کی تفصیلات دستیاب نہیں ہیں",
    introduction: "تعارف",
    biographyNotFound: "سوانح عمری نہیں ملی۔",
    failedToLoad: "سوانح عمری کا ڈیٹا لوڈ کرنے میں ناکام۔ براہ کرم بعد میں دوبارہ کوشش کریں۔",
  },
  ja: {
    cityNotAvailable: "この都市は利用できません",
    home: "ホーム",
    cityDetailsNotAvailable: "都市の詳細は利用できません",
    introduction: "紹介",
    biographyNotFound: "経歴が見つかりません。",
    failedToLoad: "経歴データの読み込みに失敗しました。後でもう一度お試しください。",
  },
};
export default biographyContent