const forgotPasswordContent = {
    title: {
        ar: "إعادة تعيين كلمة المرور",
        en: "Reset Password",
        fr: "Réinitialiser le mot de passe",
        de: "Passwort zurücksetzen",
        es: "Restablecer contraseña",
        it: "Reimposta password",
        pt: "Redefinir senha",
        ru: "Сброс пароля",
        ja: "パスワードをリセット",
        zh: "重置密码",
        ko: "비밀번호 재설정",
        hi: "पासवर्ड रीसेट करें",
    },
    emailOrPhoneLabel: {
        ar: "البريد الإلكتروني أو رقم الهاتف",
        en: "Email or Phone Number",
        fr: "E-mail ou numéro de téléphone",
        de: "E-Mail oder Telefonnummer",
        es: "Correo electrónico o número de teléfono",
        it: "Email o numero di telefono",
        pt: "E-mail ou número de telefone",
        ru: "Электронная почта или номер телефона",
        ja: "メールアドレスまたは電話番号",
        zh: "电子邮件或电话号码",
        ko: "이메일 또는 전화번호",
        hi: "ईमेल या फ़ोन नंबर",
    },
    emailOrPhonePlaceholder: {
        ar: "أدخل البريد الإلكتروني أو رقم الهاتف",
        en: "Enter your email or phone number",
        fr: "Entrez votre e-mail ou numéro de téléphone",
        de: "Geben Sie Ihre E-Mail-Adresse oder Telefonnummer ein",
        es: "Ingrese su correo electrónico o número de teléfono",
        it: "Inserisci la tua email o numero di telefono",
        pt: "Digite seu e-mail ou número de telefone",
        ru: "Введите свой адрес электронной почты или номер телефона",
        ja: "メールアドレスまたは電話番号を入力してください",
        zh: "输入您的电子邮件或电话号码",
        ko: "이메일 또는 전화번호를 입력하세요",
        hi: "अपना ईमेल या फ़ोन नंबर दर्ज करें",
    },
    newPasswordLabel: {
        ar: "كلمة المرور الجديدة",
        en: "New Password",
        fr: "Nouveau mot de passe",
        de: "Neues Passwort",
        es: "Nueva contraseña",
        it: "Nuova password",
        pt: "Nova senha",
        ru: "Новый пароль",
        ja: "新しいパスワード",
        zh: "新密码",
        ko: "새 비밀번호",
        hi: "नया पासवर्ड",
    },
    newPasswordPlaceholder: {
        ar: "أدخل كلمة المرور الجديدة",
        en: "Enter new password",
        fr: "Entrez le nouveau mot de passe",
        de: "Geben Sie ein neues Passwort ein",
        es: "Ingrese nueva contraseña",
        it: "Inserisci la nuova password",
        pt: "Digite a nova senha",
        ru: "Введите новый пароль",
        ja: "新しいパスワードを入力してください",
        zh: "输入新密码",
        ko: "새 비밀번호를 입력하세요",
        hi: "नया पासवर्ड दर्ज करें",
    },
    confirmPasswordLabel: {
        ar: "تأكيد كلمة المرور",
        en: "Confirm Password",
        fr: "Confirmer le mot de passe",
        de: "Passwort bestätigen",
        es: "Confirmar contraseña",
        it: "Conferma password",
        pt: "Confirmar senha",
        ru: "Подтвердите пароль",
        ja: "パスワードを確認",
        zh: "确认密码",
        ko: "비밀번호 확인",
        hi: "पासवर्ड की पुष्टि करें",
    },
    confirmPasswordPlaceholder: {
        ar: "أدخل تأكيد كلمة المرور",
        en: "Confirm new password",
        fr: "Confirmez le nouveau mot de passe",
        de: "Bestätigen Sie das neue Passwort",
        es: "Confirme nueva contraseña",
        it: "Conferma la nuova password",
        pt: "Confirme a nova senha",
        ru: "Подтвердите новый пароль",
        ja: "新しいパスワードを確認してください",
        zh: "确认新密码",
        ko: "새 비밀번호 확인",
        hi: "नए पासवर्ड की पुष्टि करें",
    },
    submitButton: {
        ar: "إرسال",
        en: "Submit",
        fr: "Soumettre",
        de: "Senden",
        es: "Enviar",
        it: "Invia",
        pt: "Enviar",
        ru: "Отправить",
        ja: "送信",
        zh: "提交",
        ko: "제출",
        hi: "जमा करें",
    },
    validation: {
        emailOrPhoneRequired: {
            ar: "ادخل البريد الإلكتروني أو رقم الهاتف",
            en: "Enter your email or phone number",
            fr: "Entrez votre e-mail ou numéro de téléphone",
            de: "Geben Sie Ihre E-Mail-Adresse oder Telefonnummer ein",
            es: "Ingrese su correo electrónico o número de teléfono",
            it: "Inserisci la tua email o numero di telefono",
            pt: "Digite seu e-mail ou número de telefone",
            ru: "Введите свой адрес электронной почты или номер телефона",
            ja: "メールアドレスまたは電話番号を入力してください",
            zh: "输入您的电子邮件或电话号码",
            ko: "이메일 또는 전화번호를 입력하세요",
            hi: "अपना ईमेल या फ़ोन नंबर दर्ज करें",
        },
        emailOrPhoneInvalid: {
            ar: "رقم هاتف أو بريد إلكتروني غير صحيح",
            en: "Invalid email or phone number",
            fr: "E-mail ou numéro de téléphone invalide",
            de: "Ungültige E-Mail-Adresse oder Telefonnummer",
            es: "Correo electrónico o número de teléfono no válido",
            it: "Email o numero di telefono non valido",
            pt: "E-mail ou número de telefone inválido",
            ru: "Неверный адрес электронной почты или номер телефона",
            ja: "無効なメールアドレスまたは電話番号",
            zh: "无效的电子邮件或电话号码",
            ko: "유효하지 않은 이메일 또는 전화번호",
            hi: "अमान्य ईमेल या फ़ोन नंबर",
        },
        newPasswordRequired: {
            ar: "ادخل كلمة المرور الجديدة",
            en: "Enter new password",
            fr: "Entrez le nouveau mot de passe",
            de: "Geben Sie ein neues Passwort ein",
            es: "Ingrese nueva contraseña",
            it: "Inserisci la nuova password",
            pt: "Digite a nova senha",
            ru: "Введите новый пароль",
            ja: "新しいパスワードを入力してください",
            zh: "输入新密码",
            ko: "새 비밀번호를 입력하세요",
            hi: "नया पासवर्ड दर्ज करें",
        },
        confirmPasswordRequired: {
            ar: "ادخل تأكيد كلمة المرور",
            en: "Confirm new password",
            fr: "Confirmez le nouveau mot de passe",
            de: "Bestätigen Sie das neue Passwort",
            es: "Confirme nueva contraseña",
            it: "Conferma la nuova password",
            pt: "Confirme a nova senha",
            ru: "Подтвердите новый пароль",
            ja: "新しいパスワードを確認してください",
            zh: "确认新密码",
            ko: "새 비밀번호 확인",
            hi: "नए पासवर्ड की पुष्टि करें",
        },
        passwordMismatch: {
            ar: "كلمة المرور غير متطابقة",
            en: "Passwords do not match",
            fr: "Les mots de passe ne correspondent pas",
            de: "Passwörter stimmen nicht überein",
            es: "Las contraseñas no coinciden",
            it: "Le password non corrispondono",
            pt: "As senhas não correspondem",
            ru: "Пароли не совпадают",
            ja: "パスワードが一致しません",
            zh: "密码不匹配",
            ko: "비밀번호가 일치하지 않습니다",
            hi: "पासवर्ड मेल नहीं खाते",
        },
    },
};

export default forgotPasswordContent;