const forgotPasswordContent = {
  title: {
    ar: "إعادة تعيين كلمة المرور",
    en: "Reset Password",
    fr: "Réinitialiser le mot de passe",
    de: "Passwort zurücksetzen",
    es: "Restablecer contraseña",
    tr: "Şifreyi Sıfırla",
    ru: "Сброс пароля",
    zh: "重置密码",
    ko: "비밀번호 재설정",
    pt: "Redefinir senha",
    ur: "پاس ورڈ دوبارہ ترتیب دیں",
    ja: "パスワードをリセット",
  },
  emailOrPhoneLabel: {
    ar: "البريد الإلكتروني أو رقم الهاتف",
    en: "Email or Phone Number",
    fr: "E-mail ou numéro de téléphone",
    de: "E-Mail oder Telefonnummer",
    es: "Correo electrónico o número de teléfono",
    tr: "E-posta veya Telefon Numarası",
    ru: "Электронная почта или номер телефона",
    zh: "电子邮件或电话号码",
    ko: "이메일 또는 전화번호",
    pt: "E-mail ou número de telefone",
    ur: "ای میل یا فون نمبر",
    ja: "メールアドレスまたは電話番号",
  },
  emailOrPhonePlaceholder: {
    ar: "أدخل البريد الإلكتروني أو رقم الهاتف",
    en: "Enter your email or phone number",
    fr: "Entrez votre e-mail ou numéro de téléphone",
    de: "Geben Sie Ihre E-Mail-Adresse oder Telefonnummer ein",
    es: "Ingrese su correo electrónico o número de teléfono",
    tr: "E-posta veya telefon numaranızı girin",
    ru: "Введите адрес электронной почты или номер телефона",
    zh: "输入您的电子邮件或电话号码",
    ko: "이메일 또는 전화번호를 입력하세요",
    pt: "Digite seu e-mail ou número de telefone",
    ur: "اپنا ای میل یا فون نمبر درج کریں",
    ja: "メールアドレスまたは電話番号を入力してください",
  },
  newPasswordLabel: {
    ar: "كلمة المرور الجديدة",
    en: "New Password",
    fr: "Nouveau mot de passe",
    de: "Neues Passwort",
    es: "Nueva contraseña",
    tr: "Yeni Şifre",
    ru: "Новый пароль",
    zh: "新密码",
    ko: "새 비밀번호",
    pt: "Nova senha",
    ur: "نیا پاس ورڈ",
    ja: "新しいパスワード",
  },
  newPasswordPlaceholder: {
    ar: "أدخل كلمة المرور الجديدة",
    en: "Enter new password",
    fr: "Entrez le nouveau mot de passe",
    de: "Neues Passwort eingeben",
    es: "Ingrese nueva contraseña",
    tr: "Yeni şifreyi girin",
    ru: "Введите новый пароль",
    zh: "输入新密码",
    ko: "새 비밀번호를 입력하세요",
    pt: "Digite a nova senha",
    ur: "نیا پاس ورڈ درج کریں",
    ja: "新しいパスワードを入力してください",
  },
  confirmPasswordLabel: {
    ar: "تأكيد كلمة المرور",
    en: "Confirm Password",
    fr: "Confirmer le mot de passe",
    de: "Passwort bestätigen",
    es: "Confirmar contraseña",
    tr: "Şifreyi Onayla",
    ru: "Подтвердить пароль",
    zh: "确认密码",
    ko: "비밀번호 확인",
    pt: "Confirmar senha",
    ur: "پاس ورڈ کی تصدیق کریں",
    ja: "パスワードを確認",
  },
  confirmPasswordPlaceholder: {
    ar: "أدخل تأكيد كلمة المرور",
    en: "Confirm new password",
    fr: "Confirmez le nouveau mot de passe",
    de: "Neues Passwort bestätigen",
    es: "Confirme la nueva contraseña",
    tr: "Yeni şifreyi onaylayın",
    ru: "Подтвердите новый пароль",
    zh: "确认新密码",
    ko: "새 비밀번호 확인",
    pt: "Confirme a nova senha",
    ur: "نیا پاس ورڈ دوبارہ درج کریں",
    ja: "新しいパスワードを確認してください",
  },
  submitButton: {
    ar: "إرسال",
    en: "Submit",
    fr: "Soumettre",
    de: "Senden",
    es: "Enviar",
    tr: "Gönder",
    ru: "Отправить",
    zh: "提交",
    ko: "제출",
    pt: "Enviar",
    ur: "جمع کرائیں",
    ja: "送信",
  },
  validation: {
    emailOrPhoneRequired: {
      ar: "ادخل البريد الإلكتروني أو رقم الهاتف",
      en: "Enter your email or phone number",
      fr: "Entrez votre e-mail ou numéro de téléphone",
      de: "Geben Sie Ihre E-Mail-Adresse oder Telefonnummer ein",
      es: "Ingrese su correo electrónico o número de teléfono",
      tr: "E-posta veya telefon numaranızı girin",
      ru: "Введите адрес электронной почты или номер телефона",
      zh: "输入您的电子邮件或电话号码",
      ko: "이메일 또는 전화번호를 입력하세요",
      pt: "Digite seu e-mail ou número de telefone",
      ur: "اپنا ای میل یا فون نمبر درج کریں",
      ja: "メールアドレスまたは電話番号を入力してください",
    },
    emailOrPhoneInvalid: {
      ar: "رقم هاتف أو بريد إلكتروني غير صحيح",
      en: "Invalid email or phone number",
      fr: "E-mail ou numéro de téléphone invalide",
      de: "Ungültige E-Mail-Adresse oder Telefonnummer",
      es: "Correo electrónico o número de teléfono no válido",
      tr: "Geçersiz e-posta veya telefon numarası",
      ru: "Неверный адрес электронной почты или номер телефона",
      zh: "无效的电子邮件或电话号码",
      ko: "유효하지 않은 이메일 또는 전화번호",
      pt: "E-mail ou número de telefone inválido",
      ur: "غلط ای میل یا فون نمبر",
      ja: "無効なメールアドレスまたは電話番号",
    },
    newPasswordRequired: {
      ar: "ادخل كلمة المرور الجديدة",
      en: "Enter new password",
      fr: "Entrez le nouveau mot de passe",
      de: "Neues Passwort eingeben",
      es: "Ingrese nueva contraseña",
      tr: "Yeni şifreyi girin",
      ru: "Введите новый пароль",
      zh: "输入新密码",
      ko: "새 비밀번호를 입력하세요",
      pt: "Digite a nova senha",
      ur: "نیا پاس ورڈ درج کریں",
      ja: "新しいパスワードを入力してください",
    },
    confirmPasswordRequired: {
      ar: "ادخل تأكيد كلمة المرور",
      en: "Confirm new password",
      fr: "Confirmez le nouveau mot de passe",
      de: "Neues Passwort bestätigen",
      es: "Confirme la nueva contraseña",
      tr: "Yeni şifreyi onaylayın",
      ru: "Подтвердите новый пароль",
      zh: "确认新密码",
      ko: "새 비밀번호 확인",
      pt: "Confirme a nova senha",
      ur: "نیا پاس ورڈ دوبارہ درج کریں",
      ja: "新しいパスワードを確認してください",
    },
    passwordMismatch: {
      ar: "كلمة المرور غير متطابقة",
      en: "Passwords do not match",
      fr: "Les mots de passe ne correspondent pas",
      de: "Passwörter stimmen nicht überein",
      es: "Las contraseñas no coinciden",
      tr: "Şifreler eşleşmiyor",
      ru: "Пароли не совпадают",
      zh: "密码不匹配",
      ko: "비밀번호가 일치하지 않습니다",
      pt: "As senhas não coincidem",
      ur: "پاس ورڈز مماثل نہیں ہیں",
      ja: "パスワードが一致しません",
    },
  },
};

export default forgotPasswordContent;