const otpContent = {
  title: {
    ar: "التحقق من الرمز",
    en: "Verify Code",
    fr: "Vérifier le code",
    de: "Code überprüfen",
    es: "Verificar código",
    tr: "Kodu Doğrula",
    ru: "Проверить код",
    zh: "验证码",
    ko: "코드 확인",
    pt: "Verificar Código",
    ur: "کوڈ کی تصدیق کریں",
    ja: "コードを確認する",
  },
  description: {
    ar: "لقد أرسلنا رمز التحقق إلى",
    en: "We have sent a verification code to",
    fr: "Nous avons envoyé un code de vérification à",
    de: "Wir haben einen Bestätigungscode gesendet an",
    es: "Hemos enviado un código de verificación a",
    tr: "Doğrulama kodu gönderdik",
    ru: "Мы отправили код подтверждения на",
    zh: "我们已发送验证码至",
    ko: "인증 코드를 보냈습니다",
    pt: "Enviamos um código de verificação para",
    ur: "ہم نے ایک تصدیقی کوڈ بھیجا ہے",
    ja: "確認コードを送信しました",
  },
  resendIn: {
    ar: "إعادة الإرسال في",
    en: "Resend in",
    fr: "Renvoyer dans",
    de: "Erneut senden in",
    es: "Reenviar en",
    tr: "Tekrar gönder",
    ru: "Повторная отправка через",
    zh: "重新发送于",
    ko: "다시 보내기",
    pt: "Reenviar em",
    ur: "دوبارہ بھیجیں",
    ja: "再送信",
  },
  seconds: {
    ar: "ثواني",
    en: "seconds",
    fr: "secondes",
    de: "Sekunden",
    es: "segundos",
    tr: "saniye",
    ru: "секунд",
    zh: "秒",
    ko: "초",
    pt: "segundos",
    ur: "سیکنڈ",
    ja: "秒",
  },
  resendOtp: {
    ar: "إعادة إرسال الرمز",
    en: "Resend Code",
    fr: "Renvoyer le code",
    de: "Code erneut senden",
    es: "Reenviar código",
    tr: "Kodu Tekrar Gönder",
    ru: "Отправить код повторно",
    zh: "重新发送代码",
    ko: "코드 재전송",
    pt: "Reenviar Código",
    ur: "کوڈ دوبارہ بھیجیں",
    ja: "コードを再送信",
  },
  confirmOtp: {
    ar: "تأكيد الرمز",
    en: "Confirm Code",
    fr: "Confirmer le code",
    de: "Code bestätigen",
    es: "Confirmar código",
    tr: "Kodu Onayla",
    ru: "Подтвердить код",
    zh: "确认代码",
    ko: "코드 확인",
    pt: "Confirmar Código",
    ur: "کوڈ کی تصدیق کریں",
    ja: "コードを確認",
  },
  loading: {
    ar: "جار التحميل...",
    en: "Loading...",
    fr: "Chargement...",
    de: "Wird geladen...",
    es: "Cargando...",
    tr: "Yükleniyor...",
    ru: "Загрузка...",
    zh: "加载中...",
    ko: "로드 중...",
    pt: "Carregando...",
    ur: "لوڈ ہو رہا ہے...",
    ja: "読み込み中...",
  },
  validation: {
    fullOtp: {
      ar: "الرجاء إدخال الرمز كاملاً",
      en: "Please enter the full OTP",
      fr: "Veuillez entrer le code OTP complet",
      de: "Bitte geben Sie das vollständige OTP ein",
      es: "Por favor ingrese el OTP completo",
      tr: "Lütfen OTP'nin tamamını girin",
      ru: "Пожалуйста, введите полный OTP",
      zh: "请输入完整的OTP",
      ko: "전체 OTP를 입력하십시오",
      pt: "Por favor, insira o OTP completo",
      ur: "براہ کرم مکمل OTP درج کریں",
      ja: "完全なOTPを入力してください",
    },
    wrongOtp: {
      ar: "رمز التحقق غير صحيح",
      en: "Wrong verification code",
      fr: "Code de vérification incorrect",
      de: "Falscher Bestätigungscode",
      es: "Código de verificación incorrecto",
      tr: "Yanlış doğrulama kodu",
      ru: "Неверный код подтверждения",
      zh: "错误的验证码",
      ko: "잘못된 인증 코드",
      pt: "Código de verificação incorreto",
      ur: "غلط تصدیقی کوڈ",
      ja: "間違った確認コード",
    },
  },
};

export default otpContent;