const registerContent = {
  title: {
    ar: "تسجيل حساب جديد",
    en: "Create a New Account",
    fr: "Créer un nouveau compte",
    de: "Neues Konto erstellen",
    es: "Crear una nueva cuenta",
    tr: "Yeni Hesap Oluştur",
    ru: "Создать новый аккаунт",
    zh: "创建新账户",
    ko: "새 계정 만들기",
    pt: "Criar uma nova conta",
    ur: "نیا اکاؤنٹ بنائیں",
    ja: "新しいアカウントを作成する",
  },
  email: {
    ar: "البريد الإلكتروني ",
    en: "Email or Phone Number",
    fr: "E-mail ou numéro de téléphone",
    de: "E-Mail oder Telefonnummer",
    es: "Correo electrónico o número de teléfono",
    tr: "E-posta veya Telefon Numarası",
    ru: "Электронная почта или номер телефона",
    zh: "电子邮件或电话号码",
    ko: "이메일 또는 전화번호",
    pt: "E-mail ou número de telefone",
    ur: "ای میل یا فون نمبر",
    ja: "メールアドレスまたは電話番号",
  },
  emailOrPhonePlaceholder: {
    ar: "أدخل البريد الإلكتروني ",
    en: "Enter your email or phone number",
    fr: "Entrez votre e-mail ou numéro de téléphone",
    de: "Geben Sie Ihre E-Mail-Adresse oder Telefonnummer ein",
    es: "Ingrese su correo electrónico o número de teléfono",
    tr: "E-posta veya telefon numaranızı girin",
    ru: "Введите адрес электронной почты или номер телефона",
    zh: "输入您的电子邮件或电话号码",
    ko: "이메일 또는 전화번호를 입력하세요",
    pt: "Digite seu e-mail ou número de telefone",
    ur: "اپنا ای میل یا فون نمبر درج کریں",
    ja: "メールアドレスまたは電話番号を入力してください",
  },
  submitButton: {
    ar: "إرسال رمز الامان",
    en: "Send OTP",
    fr: "Envoyer l'OTP",
    de: "OTP senden",
    es: "Enviar OTP",
    tr: "OTP Gönder",
    ru: "Отправить OTP",
    zh: "发送OTP",
    ko: "OTP 보내기",
    pt: "Enviar OTP",
    ur: "OTP بھیجیں",
    ja: "OTPを送信",
  },
  loading: {
    ar: "جار التحميل...",
    en: "Loading...",
    fr: "Chargement...",
    de: "Wird geladen...",
    es: "Cargando...",
    tr: "Yükleniyor...",
    ru: "Загрузка...",
    zh: "加载中...",
    ko: "로드 중...",
    pt: "Carregando...",
    ur: "لوڈ ہو رہا ہے...",
    ja: "読み込み中...",
  },
  alreadyHaveAccount: {
    ar: "لديك حساب بالفعل؟",
    en: "Already have an account?",
    fr: "Vous avez déjà un compte?",
    de: "Haben Sie bereits ein Konto?",
    es: "¿Ya tienes una cuenta?",
    tr: "Zaten bir hesabınız var mı?",
    ru: "Уже есть аккаунт?",
    zh: "已有账户？",
    ko: "이미 계정이 있으신가요?",
    pt: "Já tem uma conta?",
    ur: "پہلے سے ہی ایک اکاؤنٹ ہے؟",
    ja: "すでにアカウントをお持ちですか？",
  },
  loginLink: {
    ar: "تسجيل الدخول",
    en: "Log In",
    fr: "Se connecter",
    de: "Anmelden",
    es: "Iniciar sesión",
    tr: "Giriş Yap",
    ru: "Войти",
    zh: "登录",
    ko: "로그인",
    pt: "Entrar",
    ur: "لاگ ان کریں",
    ja: "ログイン",
  },
  validation: {
    emailOrPhoneRequired: {
      ar: "ادخل البريد الإلكتروني ",
      en: "Enter your email or phone number",
      fr: "Entrez votre e-mail ou numéro de téléphone",
      de: "Geben Sie Ihre E-Mail-Adresse oder Telefonnummer ein",
      es: "Ingrese su correo electrónico o número de teléfono",
      tr: "E-posta veya telefon numaranızı girin",
      ru: "Введите адрес электронной почты или номер телефона",
      zh: "输入您的电子邮件或电话号码",
      ko: "이메일 또는 전화번호를 입력하세요",
      pt: "Digite seu e-mail ou número de telefone",
      ur: "اپنا ای میل یا فون نمبر درج کریں",
      ja: "メールアドレスまたは電話番号を入力してください",
    },
    emailOrPhoneInvalid: {
      ar: "رقم هاتف أو بريد إلكتروني غير صحيح",
      en: "Invalid email or phone number",
      fr: "E-mail ou numéro de téléphone invalide",
      de: "Ungültige E-Mail-Adresse oder Telefonnummer",
      es: "Correo electrónico o número de teléfono no válido",
      tr: "Geçersiz e-posta veya telefon numarası",
      ru: "Неверный адрес электронной почты или номер телефона",
      zh: "无效的电子邮件或电话号码",
      ko: "유효하지 않은 이메일 또는 전화번호",
      pt: "E-mail ou número de telefone inválido",
      ur: "غلط ای میل یا فون نمبر",
      ja: "無効なメールアドレスまたは電話番号",
    },
    phoneInvalid: {
      ar: "رقم الهاتف غير صحيح",
      en: "Invalid phone number",
      fr: "Numéro de téléphone invalide",
      de: "Ungültige Telefonnummer",
      es: "Número de teléfono no válido",
      tr: "Geçersiz telefon numarası",
      ru: "Неверный номер телефона",
      zh: "无效的电话号码",
      ko: "유효하지 않은 전화번호",
      pt: "Número de telefone inválido",
      ur: "غلط فون نمبر",
      ja: "無効な電話番号",
    },
  },
};

export default registerContent;